# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python chenqun-docker application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  container-run-test:

    runs-on: [self-hosted, linux, x64, chenqun]
    container:
      image: 10.101.12.128/framework/ubuntu:22.04-official
      options: --privileged
      
      credentials:
        username: admin
        password: admin@ZJ2023
      env: 
        NODE_ENV: developement
      volumes:
        - /home/songquanheng:/home/songquanheng
      
      ports:
        - 22
        - 8888

    steps:
    
    - name: show python version
      run: |
        python --version
        
    - name: show working directory before checkout
      run: |
        pwd
    - uses: actions/checkout@v3
    - name: list the files after checkout
      run: | 
        ls -R
    - name: show working directory
      run: |
        pwd

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest and generate coverage report 
      run: |
        pytest --cov=src --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: yanchenmochen/ActionPractice
        
